services:
  nginx:
    build: ./nginx
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-docker.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      ground-station-api:
        condition: service_healthy
    networks:
      - frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost/nginx-health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  ground-station-api:
    build:
      context: ./service-a
    container_name: ground-station-api
    environment:
      - TELEMETRY_PARSER_URL=http://telemetry-parser:3002/parse
      - ANOMALY_DETECTOR_URL=http://anomaly-detector:3003/analyze
    depends_on:
      telemetry-parser:
        condition: service_healthy
      anomaly-detector:
        condition: service_healthy
    networks:
      - frontend
      - backend
    restart: unless-stopped

  telemetry-parser:
    build:
      context: ./service-b
    container_name: telemetry-parser
    environment:
      - ANOMALY_DETECTOR_URL=http://anomaly-detector:3003/analyze
    networks:
      - backend
    restart: unless-stopped

  anomaly-detector:
    build:
      context: ./service-c
    container_name: anomaly-detector
    environment:
      - GROUND_STATION_CALLBACK_URL=http://ground-station-api:3001/callback
    networks:
      - backend
    restart: unless-stopped

networks:
  frontend:
  backend:
    internal: true



